apiVersion: apps/v1
kind: Deployment
metadata:
  name: vexination-api
  labels:
    app.kubernetes.io/name: vexination-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: vexination
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: vexination-api
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: vexination
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vexination-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: vexination
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - image: ghcr.io/trustification/trust:latest
          imagePullPolicy: Always
          name: service
          command: ["/trust"]
          args: ["vexination", "api", "-p", "8080"]
          env:
            - name: RUST_LOG
              value: info
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: vexination-credentials-secret
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: vexination-credentials-secret
                  key: secret-access-key
            - name: AWS_REGION
              value: "eu-west-1"
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
