appDomain: change-me

partOf: trustification
replicas: 1

image:
  registry: ghcr.io/trustification
  pullPolicy: IfNotPresent
  version: ea3d3de1d3a01c80497d9a4e4697afbc6a04591f

ingress: {}

openshift:
  enabled: false
  useServiceCa: true

oidc:
  clients:
    frontend:
      clientId: frontend
    walker:
      clientId: walker
      clientSecret:

metrics:
  enabled: false

tracing:
  enabled: false

modules:

  documentation:
    enabled: true
    ingress: {}
    image: {}
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "64Mi"

  bombasticApi:
    enabled: true
    ingress: {}
    image: {}
    tracing: {}
    metrics: {}

  bombasticCollector:
    enabled: true
    image: {}

  bombasticIndexer:
    enabled: true
    image: {}
    metrics: {}

  spogApi:
    enabled: true
    image: {}
    ingress: {}
    tracing: {}
    metrics: {}
    uiConfiguration:
      content:
        global:
          productName: All Chickens

  spogUi:
    enabled: true
    image: { }
    ingress: { }
