appDomain: change-me

partOf: trustification
replicas: 1

image:
  name: trust
  registry: ghcr.io/trustification
  pullPolicy: IfNotPresent
  version: f8005acc1848bb72f2dbe0ecffa175c59b24eeca

guac:
  image:
    name: guac
    registry: ghcr.io/trustification
    pullPolicy: IfNotPresent
    version: "v0.3.26"
  database: {}

rust: {}

ingress: {}

storage: {}

index:
  mode: file
  syncInterval: "1m"
  writerMemoryBytes: "128MiB"

openshift:
  useServiceCa: true

oidc:
  clients:
    frontend:
      clientId: frontend
    walker:
      clientId: walker
      clientSecret:

serviceMonitor:
  enabled: false

metrics:
  enabled: false

tracing:
  enabled: false

bombastic:
  bucket: bombastic
  topics:
    stored: sbom-stored
    failed: sbom-failed
    indexed: sbom-indexed

vexination:
  bucket: vexination
  topics:
    stored: vex-stored
    failed: vex-failed
    indexed: vex-indexed

v11y:
  bucket: v11y
  topics:
    stored: v11y-stored
    failed: v11y-failed
    indexed: v11y-indexed

modules:

  documentation:
    enabled: true
    ingress: {}
    image: {}
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "64Mi"

  bombasticApi:
    enabled: true
    ingress: {}
    image: {}
    tracing: {}
    metrics: {}
    rust: {}

  bombasticCollector:
    enabled: true
    image: {}

  bombasticIndexer:
    enabled: true
    image: {}
    tracing: {}
    metrics: {}
    rust: {}

  bombasticWalker:
    enabled: true
    image: {}
    sources: {}
    rust: {}

  spogApi:
    enabled: true
    image: {}
    ingress: {}
    tracing: {}
    metrics: {}
    rust: {}

  spogUi:
    enabled: true
    image: {}
    ingress: {}
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "64Mi"

  vexinationApi:
    enabled: true
    ingress: {}
    image: {}
    tracing: {}
    metrics: {}
    rust: {}

  vexinationIndexer:
    enabled: true
    image: {}
    tracing: {}
    metrics: {}
    rust: {}

  vexinationCollector:
    enabled: true
    image: {}

  vexinationWalker:
    enabled: true
    image: {}
    sources: {}
    rust: {}

  v11yApi:
    enabled: true
    ingress: {}
    image: {}
    tracing: {}
    metrics: {}
    rust: {}

  v11yIndexer:
    enabled: true
    image: {}
    tracing: {}
    metrics: {}
    rust: {}

  v11yWalker:
    enabled: true
    image: {}
    tracing: {}
    metrics: {}
    rust: {}
    storageSize: 10Gi

  guacGraphql:
    enabled: true
    image: {}

  guacCollectsub:
    enabled: false
    image: {}

  guacInitDb:
    enabled: true
    image: {}

  initDataset:
    enabled: true
    image: {}

  integrationTests:
    enabled: false
    image: {}
    rust: {}
