$schema: "http://json-schema.org/draft-07/schema#"
title: "Trustification Helm chart values"
type: object
additionalProperties: false
required:
  - appDomain
  - tracing
properties:

  appDomain:
    type: string

  partOf:
    type: string

  storage:
    $ref: "#/definitions/Storage"

  postgresql:
    $ref: "#/definitions/Postgresql"

  image:
    $ref: "#/definitions/ImageConfig"

  authenticator:
    $ref: "#/definitions/AuthenticatorConfig"

  openshift:
    type: object
    additionalProperties: false
    properties:
      enabled:
        type: boolean
      useServiceCa:
        type: boolean
        default: true

  oidc:
    $ref: "#/definitions/Oidc"

  replicas:
    type: integer
    minimum: 0

  ingress:
    type: object
    additionalProperties: false
    properties:
      className:
        type: string

  metrics:
    type: object
    additionalProperties: false
    properties:
      enabled:
        type: boolean

  tracing:
    type: object
    additionalProperties: false
    properties:
      enabled:
        type: boolean

  rustLogFilter:
    type: string

  modules:
    type: object
    additionalProperties: false
    properties:
      documentation:
        allOf:
          - $ref: "#/definitions/Feature"
          - $ref: "#/definitions/Image"
          - $ref: "#/definitions/Ingress"
          - $ref: "#/definitions/Application"
      bombasticApi:
        allOf:
          - $ref: "#/definitions/Feature"
          - $ref: "#/definitions/Image"
          - $ref: "#/definitions/Ingress"
          - $ref: "#/definitions/Application"
          - $ref: "#/definitions/RustApplication"
          - $ref: "#/definitions/Authenticator"
          - $ref: "#/definitions/Metrics"
          - $ref: "#/definitions/Tracing"
      bombasticCollector:
        allOf:
          - $ref: "#/definitions/Feature"
          - $ref: "#/definitions/Image"
          - $ref: "#/definitions/Application"
          - $ref: "#/definitions/RustApplication"
      bombasticIndexer:
        allOf:
          - $ref: "#/definitions/Feature"
          - $ref: "#/definitions/Image"
          - $ref: "#/definitions/Application"
          - $ref: "#/definitions/RustApplication"
          - $ref: "#/definitions/Metrics"

      spogApi:
        allOf:
          - $ref: "#/definitions/Feature"
          - $ref: "#/definitions/Image"
          - $ref: "#/definitions/Ingress"
          - $ref: "#/definitions/Application"
          - $ref: "#/definitions/RustApplication"
          - $ref: "#/definitions/Authenticator"
          - $ref: "#/definitions/Metrics"
          - $ref: "#/definitions/Tracing"
          - type: object
            properties:
              crdaUrl:
                type: string
                format: url
              snykToken:
                type: string
              segmentWriteKey:
                type: string
              disableSwaggerOidc:
                type: boolean
          - type: object
            properties:
              uiConfiguration:
                $ref: "#/definitions/SpogUiConfiguration"

      spogUi:
        allOf:
          - $ref: "#/definitions/Feature"
          - $ref: "#/definitions/Image"
          - $ref: "#/definitions/Ingress"
          - $ref: "#/definitions/Application"

# for infrastructure

  kafka:
    $ref: "#/definitions/Feature"

  minio:
    $ref: "#/definitions/Feature"

  keycloak:
    $ref: "#/definitions/Feature"

  postgres:
    $ref: "#/definitions/Feature"

definitions:

  Application:
    type: object
    properties:
      replicas:
        type: integer
        minimum: 0
      resources:
        type: object

  RustApplication:
    type: object
    properties:
      logFilter:
        type: string

  Metrics:
    type: object
    required:
      - metrics
    properties:
      tracing:
        $ref: "#/definitions/MetricsConfig"

  MetricsConfig:
    type: object
    additionalProperties: false
    properties:
      enabled:
        type: boolean

  Tracing:
    type: object
    required:
      - tracing
    properties:
      tracing:
        $ref: "#/definitions/TracingConfig"

  TracingConfig:
    type: object
    additionalProperties: false
    properties:
      enabled:
        type: boolean

  Image:
    type: object
    required:
      - image
    properties:
      image:
        $ref: "#/definitions/ImageConfig"

  ImageConfig:
    type: object
    additionalProperties: false
    properties:
      registry:
        type: string
      pullPolicy:
        type: string
        enum:
          - IfNotPresent
          - Always
          - Never
      version:
        type: string

  Ingress:
    type: object
    required:
      - ingress
    properties:
      ingress:
        $ref: "#/definitions/IngressConfig"

  IngressConfig:
    type: object
    additionalProperties: false
    properties:
      className:
        type: string

  Feature:
    type: object
    properties:
      enabled:
        type: boolean

  Storage:
    type: object
    properties: {}

  Postgresql:
    type: object
    properties: {}

  Authenticator:
    type: object
    properties:
      authenticator:
        $ref: "#/definitions/AuthenticatorConfig"

  AuthenticatorConfig:
    oneOf:
      - type: string
      - $ref: "#/definitions/ConfigMapRef"
      - type: object
        additionalProperties: false
        required:
          - content
        properties:
          content:
            $ref: "https://raw.githubusercontent.com/trustification/trustification/main/auth/schema/auth.json"

  Oidc:
    type: object
    additionalProperties: false
    properties:
      issuerUrl:
        type: string
        format: uri

      insecure:
        type: boolean
        description: Use insecure TLS when communicating with the issuer (DANGER!)
        default: false

      clients:
        properties:
          frontend:
            $ref: "#/definitions/OidcPublicClient"
          walker:
            $ref: "#/definitions/OidcSecretClient"

  OidcClient:
    type: object
    properties:
      clientId:
        type: string
      issuerUrl:
        type: string
        format: url
      insecure:
        type: boolean
        description: Use insecure TLS when communicating with the issuer (DANGER!)
        default: false

  OidcPublicClient:
    allOf:
      - $ref: "#/definitions/OidcClient"

  OidcSecretClient:
    allOf:
      - $ref: "#/definitions/OidcClient"
      - type: object
        required:
          - clientSecret
        properties:
          clientSecret:
            oneOf:
              - type: "null"
              - type: string
              - $ref: "#/definitions/ValueOrRef"

  ValueOrRef:
    oneOf:
      - type: object
        additionalProperties: false
        required:
          - valueFrom
        properties:
          valueFrom:
            $ref: "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/_definitions.json#/definitions/io.k8s.api.core.v1.EnvVarSource"

      - type: object
        additionalProperties: false
        required:
          - value
        properties:
          value:
            type: string

  SpogUiConfiguration:
    oneOf:
      - type: string
        description: The configuration provided as a string (must still be YAML)
      - $ref: "#/definitions/ConfigMapRef"
      - type: object
        additionalProperties: false
        required:
          - content
        description: The actual configuration
        properties:
          content:
            $ref: "https://raw.githubusercontent.com/trustification/trustification/main/spog/model/schema/config.json"

  ConfigMapRef:
    type: object
    additionalProperties: false
    required:
      - configMapRef
    properties:
      configMapRef:
        type: object
        additionalProperties: false
        required:
          - name
        properties:
          name:
            type: string
            description: The name of the config map
          key:
            type: string
            description: The name of the key inside the config map
