appDomain: change-me

partOf: trustification
replicas: 1

image:
  registry: ghcr.io/trustification
  pullPolicy: IfNotPresent
  version: ea3d3de1d3a01c80497d9a4e4697afbc6a04591f

ingress: {}

storage: {}

index:
  mode: file
  syncInterval: "1m"
  writerMemoryBytes: "128MiB"

openshift:
  enabled: false
  useServiceCa: true

oidc:
  clients:
    frontend:
      clientId: frontend
    walker:
      clientId: walker
      clientSecret:

metrics:
  enabled: false

tracing:
  enabled: false

bombastic:
  bucket: bombastic
  topics:
    stored: sbom-stored
    failed: sbom-failed
    indexed: sbom-indexed

vexination:
  bucket: vexination
  topics:
    stored: vex-stored
    failed: vex-failed
    indexed: vex-indexed

v11y:
  bucket: v11y
  topics:
    stored: v11y-stored
    failed: v11y-failed
    indexed: v11y-indexed

modules:

  documentation:
    enabled: true
    ingress: {}
    image: {}
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "64Mi"

  bombasticApi:
    enabled: true
    ingress: {}
    image: {}
    tracing: {}
    metrics: {}

  bombasticCollector:
    enabled: true
    image: {}

  bombasticIndexer:
    enabled: true
    image: {}
    tracing: {}
    metrics: {}

  spogApi:
    enabled: true
    image: {}
    ingress: {}
    tracing: {}
    metrics: {}
    uiConfiguration:
      content:
        global:
          productName: All Chickens

  spogUi:
    enabled: true
    image: {}
    ingress: {}
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "64Mi"

  vexinationApi:
    enabled: true
    ingress: {}
    image: {}
    tracing: {}
    metrics: {}

  vexinationIndexer:
    enabled: true
    image: {}
    tracing: {}
    metrics: {}

  v11yApi:
    enabled: true
    ingress: {}
    image: {}
    tracing: {}
    metrics: {}

  v11yIndexer:
    enabled: true
    image: {}
    tracing: {}
    metrics: {}

  v11yWalker:
    enabled: true
    image: {}
    gitImage:
      version: "2.40.1"
    tracing: {}
    metrics: {}
    storageSize: 10Gi
