{{- if and .Values.modules.bombasticApi.enabled }}
{{- $mod := dict "root" . "name" "bombastic-api" "component" "bombastic" "module" .Values.modules.bombasticApi -}}
{{- include "trustification.ingress.defaultIngress" ( set (deepCopy $mod) "host" (include "trustification.host.bombasticApi" $mod ) ) }}
{{- end }}
