[package]
name = "bombastic-index"
version = "0.1.0"
edition = "2021"

[dependencies]
sikula = { version = "0.3", features = ["time"] }
zstd = "0.12"
tantivy = "0.19.2"
tracing = "0.1"
chumsky = "1.0.0-alpha.4"
time = "0.3"
tar = "0.4"
trustification-index = { path = "../../index" }
cyclonedx-bom = "0.4.0"
spdx-rs = "0.5.2"
packageurl = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
