[package]
name = "trustification-index"
version = "0.1.0"
edition = "2021"

[dependencies]
tantivy = "0.19.2"
log = "0.4"
zstd = "0.12"
tar = "0.4"
sikula = { version = "0.3", features = ["time"] }
time = "0.3"
clap = { version = "4", features = ["derive", "env"] }
humantime = "2.1.0"
rand = "0.8"
prometheus = "0.13.3"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
env_logger = "0.10"
