[package]
name = "v11y-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
trustification-event-bus = { path = "../../event-bus" }
trustification-infrastructure = { path = "../../infrastructure" }
trustification-storage = { path = "../../storage" }
trustification-index = { path = "../../index" }
trustification-indexer = { path = "../../indexer" }

v11y-model = { path = "../model" }
v11y-index = { path = "../index" }