[package]
name = "v11y-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1"
chrono = "0.4.26"
clap = { version = "4", features = ["derive"] }
cve = "0.2.1"
futures = "0.3"
humantime = "2"
humantime-serde = "1.1.1"
time = { version = "0.3", features = ["parsing", "formatting"] }
log = "0.4"
prometheus = "0.13.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
sqlx = { version = "0.7.0", features = ["runtime-tokio", "sqlite", "chrono"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
trustification-event-bus = { path = "../../event-bus" }
trustification-infrastructure = { path = "../../infrastructure" }
trustification-storage = { path = "../../storage" }
trustification-index = { path = "../../index" }
trustification-indexer = { path = "../../indexer" }
walkdir = "2"
env_logger = "0.11"

v11y-model = { path = "../model" }
v11y-index = { path = "../index" }