[package]
name = "vexination-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
vexination-index = { path = "../index" }
trustification-event-bus = { path = "../../event-bus" }
trustification-infrastructure = { path = "../../infrastructure" }
trustification-storage = { path = "../../storage" }
trustification-index = { path = "../../index" }
trustification-indexer = { path = "../../indexer" }
csaf = "0.5"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
