{{- if .Values.modules.guacGraphql.enabled }}
{{- $mod := dict "root" . "name" "guac-graphql" "component" "guac" "module" .Values.modules.guacGraphql -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "trustification.common.selectorLabels" $mod | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              "kubernetes.io/metadata.name": {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: 8080
    - from:
      - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 9010
{{- end }}
