[package]
name = "v11y-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
v11y-client = { path = "../client" }
trustification-auth = { path = "../../auth", features = ["actix", "swagger"] }
trustification-infrastructure = { path = "../../infrastructure" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
derive_more = "0.99"
futures = "0.3"
log = "0.4"
utoipa = { version = "3", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "3", features = ["actix-web"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.7.0", features = ["runtime-tokio", "sqlite", "chrono"] }
reqwest = "0.11.18"
chrono = "0.4.26"
humantime = "2"
humantime-serde = "1.1.1"
prometheus = "0.13.3"
actix-web-httpauth = "0.8.0"
actix-web-prom = "0.6.0"
actix-cors = "0.6"

[dev-dependencies]
env_logger = "0.10"

