[package]
name = "v11y-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
v11y-model = { path = "../model" }
v11y-index = { path = "../index" }
trustification-api = { path = "../../api" }
trustification-auth = { path = "../../auth", features = ["actix", "swagger"] }
trustification-common = { path = "../../common" }
trustification-infrastructure = { path = "../../infrastructure" }
trustification-index = { path = "../../index" }
trustification-storage = { path = "../../storage" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
thiserror = "1"
derive_more = "0.99"
log = "0.4"
utoipa = { version = "4", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "4", features = ["actix-web"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }
prometheus = "0.13.3"
actix-web-httpauth = "0.8.0"
sha1 = "0.10.5"

[dev-dependencies]
env_logger = "0.11"
tempdir = "0.3.7"

