[workspace]
members = [
    "analytics",
    "api",
    "auth",
    "bombastic/bombastic",
    "bombastic/api",
    "bombastic/model",
    "bombastic/indexer",
    "bombastic/index",
    "bombastic/walker",
    "bommer",
    "bommer/bommer-api",
    "common",
    "vexination/vexination",
    "vexination/api",
    "vexination/index",
    "vexination/model",
    "vexination/indexer",
    "vexination/walker",
    "reservoir/reservoir",
    "reservoir/api",
    "spog/api",
    "spog/model",
    "spog/spog",
    "exhort/api",
    "exhort/exhort",
    "collectorist/api",
    "collectorist/collectorist",
    "collectorist/client",
    "collector/collector",
    "collector/client",
    "collector/osv",
    "collector/snyk",
    "collector/nvd",
    "v11y/api",
    "v11y/client",
    "v11y/model",
    "v11y/v11y",
    "integration-tests",
    "trust",
    "exporter",
    "event-bus",
    "storage",
    "index",
    "infrastructure",
    "version",
    "admin",
    "indexer",
]
default-members = [
    "analytics",
    "auth",
    "bombastic/bombastic",
    "bombastic/api",
    "bombastic/model",
    "bombastic/indexer",
    "bombastic/index",
    "bommer",
    "bommer/bommer-api",
    "common",
    "vexination/vexination",
    "vexination/api",
    "vexination/index",
    "vexination/model",
    "vexination/indexer",
    "vexination/walker",
    "reservoir/reservoir",
    "reservoir/api",
    "spog/api",
    "spog/model",
    "spog/spog",
    "exhort/api",
    "exhort/exhort",
    "collectorist/api",
    "collectorist/collectorist",
    "collectorist/client",
    "collector/collector",
    "collector/client",
    "collector/osv",
    "collector/snyk",
    "collector/nvd",
    "v11y/api",
    "v11y/client",
    "v11y/model",
    "v11y/v11y",
    "trust",
    "exporter",
    "event-bus",
    "storage",
    "index",
    "infrastructure",
    "version",
    "indexer",
]

[workspace.dependencies]
guac = { git = "https://github.com/trustification/guac-rs.git", rev = "5b8cad8342d42072a72ef4a149348d0d86a84176" }
#guac = { path = "../guac-rs/lib" }

[patch.crates-io]
#tantivy = { path = "../tantivy" }
#sikula = { git = "https://github.com/ctron/sikula", rev = "cea7429f6b690adcdcd1ce2edb2b9e2277834e03" }
#sikula = { path = "../sikula" }

csaf = { git = "https://github.com/voteblake/csaf-rs", rev = "76cb9ede10adb1fbb495b17e5fd8d95c5cf6c900" } # FIXME: waiting for release

# also check: spog/ui/Cargo.toml
cyclonedx-bom = { git = "https://github.com/trustification/cyclonedx-rust-cargo", branch = "trustification" }
spdx-rs = { git = "https://github.com/trustification/spdx-rs", rev = "c65be086e898dae88609f07bbc5a224ba4e0838d" } # FIXME: awaiting doubleopen-project/spdx-rs#/27

