{{- if .Values.modules.spogUi.enabled }}
{{- $mod := dict "root" . "name" "spog-ui-backend" "component" "spog" "module" .Values.modules.spogUi -}}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}

data:

{{- if $mod.initialBackendJson }}{{/* Explicit content section */}}

{{- if kindIs "string" . }}
  backend.json: {{ . | quote }}
{{- else }}
  backend.json: {{ . | toJson | quote }}
{{- end }}

{{- else }}{{/* Some reasonble defaults */}}

{{- if  eq (.Values.authenticator).type "cognito" }}
  backend.json: |
    { "oidc": {
      "end_session_url": "{{ .Values.authenticator.cognitoDomainUrl }}/logout?client_id={{ include "trustification.oidc.frontendClientId" . }}",
      "post_logout_redirect_name": "logout_uri",
      "redirect_url": "{{ include "trustification.tls.http.protocol" $mod }}://{{ include "trustification.host.spogUi" $mod }}"
    }}
{{- end }}

{{- end }}

{{- end}}
