{{- if .Values.modules.spogUi.enabled }}
{{- $mod := dict "root" . "name" "spog-ui" "component" "spog" "module" .Values.modules.spogUi -}}
{{- include "trustification.application.defaultService" $mod }}
{{- end }}