openapi: 3.0.3
info:
  title: Bombastic API
  description: Bombastic API
  version: 0.1.0
servers:
  - url: 'https'
paths:
  /api/v1/sbom:
    get:
      description: Query sboms
      parameters:
        - $ref: '#/components/parameters/PurlQueryParam'
      responses:
        200:
          description: The SBOM content
        400:
          description: Missing valid purl or index entry
        404:
          description: SBOM not found in archive
    post:
      description: Publish sboms
      parameters:
        - $ref: '#/components/parameters/PurlQueryParam'
        - name: transfer-encoding
          in: header
          description: |
            Enable chunked transfer for large SBOMs. 
            Values other than `chunked` will be ignored
          content:
            text/plain:
              example: "Chunked"
      responses:
        201:
          description: The SBOM content was stored successfully.
          content:
              text/plain:
                schema:
                  type: string
                example: 'SBOM of size 42 stored successfully'
        400:
          description: | 
            The uploaded SBOM was invalid, or the Purl or Sha 256 were not found.
            The response may contain more information about the issue.
          content:
            text/plain:
              schema:
                type: string
                example: No pURL found
        500:
          description: Service error


components:
  parameters:
    PurlQueryParam:
      name: purl
      in: query
      description: The package URL of the SBOM
      content:
        text/plain:
          example: pkg:github/package-url/purl-spec@244fd47e07d1004f0aed9c
