## Trustification

tracing: {}
appDomain: change-me

storage:
  endpoint: http://infrastructure-minio.trustification.svc.cluster.local.:9000
  accessKey:
    valueFrom:
      secretKeyRef:
        name: infrastructure-minio
        key: root-user
  secretKey:
    valueFrom:
      secretKeyRef:
        name: infrastructure-minio
        key: root-password

eventBus:
  type: kafka
  bootstrapServers: infrastructure-kafka.trustification.svc.cluster.local.:9092

## Infrastructure

minio:
  enabled: true
  rootPassword: minio123456

keycloak:
  enabled: true
  production: false
  auth:
    adminUser: admin
    adminPassword: admin123456
  tls:
    enabled: false
  service: {}
  ingress:
    enabled: true
    servicePort: http

# NOTE: the following "secrets" are obviously not SECRET. So don't rely on them except for maybe local testing.
oidc:
  clients:
    frontend: {}
    walker:
      clientSecret:
        value: 5460cc91-4e20-4edd-881c-b15b169f8a79
    testingUser:
      clientSecret:
        value: 0e6bf990-43b4-4efb-95d7-b24f2b94a525
    testingManager:
      clientSecret:
        value: ca48053c-3b82-4650-a98d-4cace7f2d567

postgres:
  enabled: true
  auth:
    postgresPassword: postgres123456
    username: trustification
    password: postgres1234

kafka:
  enabled: true
  kraft:
    clusterId: "3nA2qspzReOmcxqlkmITAA"
