## Trustification



## Infrastructure

minio:
  enabled: true
  rootPassword: minio123456

keycloak:
  enabled: true
  production: false
  auth:
    adminUser: admin
    adminPassword: admin123456
  tls:
    enabled: false
  service: {}
  ingress:
    enabled: true
    hostname: sso.trustification.dev
    servicePort: http

postgres:
  enabled: true
  auth:
    postgresPassword: postgres123456
    username: trustification
    password: postgres1234

kafka:
  enabled: true
  kraft:
    clusterId: "3nA2qspzReOmcxqlkmITAA"
