[package]
name = "trustification-auth"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Authentication and authorization functionality"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"]}
log = "0.4"
openid = "0.12"
# openidconnect = { version = "3.3", default-features = false, features = ["reqwest", "native-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tracing = "0.1"
futures-util = "0.3"
reqwest = "0.11"
chrono = { version = "0.4.26", default-features = false }
url = "2"

trustification-common = { path = "../common" }

actix-web = { version = "4.3.1", optional = true }
actix-http = { version = "3.3.1", optional = true }
actix-web-httpauth = { version = "0.8", optional = true }
actix-web-extras = { version = "0.1", optional = true }

[features]
default = []
actix = ["actix-web", "actix-http", "actix-web-httpauth", "actix-web-extras"]
