apiVersion: v1
kind: ConfigMap
metadata:
  name: spog-ui-branding
  labels:
    app.kubernetes.io/name: spog-ui-branding
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: trustification
binaryData:
  {{- range $path, $content := .Files.Glob "files/branding/**" }}
  {{ base $path }}: {{ $content | toJson }}
  {{- end }}
