[package]
name = "collectorist-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
trustification-infrastructure = { path = "../../infrastructure" }
collectorist-client = { path = "../client"}
collector-client = { path = "../../collector/client"}
clap = { version = "4", features = ["derive"] }
anyhow = "1"
derive_more = "0.99"
futures = "0.3"
log = "0.4"
utoipa = { version = "3", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "3", features = ["actix-web"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }
guac = "0.1"
sqlx = { version = "0.7.0", features = [ "runtime-tokio", "sqlite", "chrono"] }
reqwest = "0.11.18"
chrono = "0.4.26"
humantime = "2"
humantime-serde = "1.1.1"


[dev-dependencies]
env_logger = "0.10"

#[build-dependencies]
#tonic-build = "0.9.2"
