[package]
name = "collectorist-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
trustification-infrastructure = { path = "../../infrastructure" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
derive_more = "0.99"
futures = "0.3"
log = "0.4"
utoipa = { version = "3", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "3", features = ["actix-web"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }
guac = { git = "https://github.com/dejanb/guac-rs.git", branch = "main" }


[dev-dependencies]
env_logger = "0.10"

[build-dependencies]
tonic-build = "0.9.2"
