{{- if and .Values.modules.bombasticCollector.enabled }}
{{- $mod := dict "root" . "name" "bombastic-collector" "component" "guac" "module" .Values.modules.bombasticCollector -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
  annotations:
    {{- include "trustification.application.annotations" $mod | nindent 4 }}

spec:
  replicas: 1 # only run one
  strategy:
    type: Recreate

  selector:
    matchLabels:
      {{- include "trustification.common.selectorLabels" $mod | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "trustification.common.selectorLabels" $mod | nindent 8 }}
        {{- include "trustification.application.podLabels" $mod | nindent 8 }}

    spec:
      {{- include "trustification.application.pod" $mod | nindent 6 }}

      containers:
        - name: service
          {{- include "trustification.guac.defaultImage" $mod | nindent 10 }}
          {{- include "trustification.application.container" $mod | nindent 10 }}

          command: ["/opt/guac/guacone"]
          args:
            - collect
            - s3
            - --poll

          env:
            {{- include "trustification.storage.guac.envVars" ( set (deepCopy $mod) "storage" .Values.bombastic) | nindent 12 }}
            {{- include "trustification.eventBus.guac.envVars" $mod | nindent 12 }}

            - name: GUAC_S3_QUEUES
              value: {{ ($mod.module.topics).indexed | default .Values.bombastic.topics.indexed | quote }}

            - name: GUAC_GQL_ADDR
              value: {{ include "trustification.tls.http.protocol" $mod }}://guac-graphql.{{ .Release.Namespace }}.svc.cluster.local/query
            - name: GUAC_CSUB_ADDR
              value: guac-collectsub.{{ .Release.Namespace }}.svc.cluster.local:2782

{{- end }}
