$schema: "http://json-schema.org/draft-07/schema#"
$id: "uri:trustification:spog:ui:config"
title: "SPoG UI configuration file schema"

type: object

additionalProperties: false

properties:

  "$schema":
    type: string

  landingPage:
    type: object
    additionalProperties: false
    description: |
      Allows to customize the entry page. Part of this can be HTML blocks to inject into the main page. These elements
      can leverage PatternFly classes to visually style the representation.
    properties:
      headerContent:
        type: string
        description: |
          HTML content injected before the main search entry box.
      beforeOuterContent:
        type: string
        description: |
          HTML content injected before the entry field, outside the main entry box.
      beforeInnerContent:
        type: string
        description: |
          HTML content injected before the entry field, inside the main entry box.
      afterInnerContent:
        type: string
        description: |
          HTML content injected after the entry field, inside the main entry box.
      afterOuterContent:
        type: string
        description: |
          HTML content injected after the entry field, outside the main entry box.
      footerContent:
        type: string
        description: |
          HTML content injected after the main search entry box.

  bombastic:
    type: object
    additionalProperties: false
    properties:
      filters:
        $ref: "#/definitions/filters"

  vexination:
    type: object
    additionalProperties: false
    properties:
      filters:
        $ref: "#/definitions/filters"

  global:
    $ref: "#/definitions/global"

definitions:

  global:
    type: object
    additionalProperties: false
    properties:
      documentationUrl:
        type: string
        format: url
      supportUrl:
        type: string
        format: url

  filters:
    type: object
    properties:
      categories:
        type: array
        items:
          $ref: "#/definitions/category"

  category:
    type: object
    additionalProperties: false
    properties:
      label:
        type: string
      options:
        type: array
        items:
          $ref: "#/definitions/option"
    required:
      - label

  option:
    oneOf:
      - $ref: "#/definitions/checkOption"
      - $ref: "#/definitions/divider"

  divider:
    type: object
    additionalProperties: false
    properties:
      divider:
        type: boolean
        const: true

  checkOption:
    type: object
    additionalProperties: false
    properties:
      id:
        type: string
        description: A unique ID of the option
      label:
        type: string
      terms:
        type: array
        items:
          type: string
    required:
      - id
      - label
      - terms
