[package]
name = "spog-ui"
version = "0.1.0"
edition = "2021"
license = "Apache-2"
# Will be present in the about dialog too
description = "Single Pane of Glass"

[dependencies]
anyhow = "1"
async-trait = "0.1"
browser-panic-hook = "0.2.0"
chrono = { version = "0.4", default-features = false, features = ["wasmbind"] }
csaf = { version = "0.5.0", default-features = false }
cvss = { version = "2", features = ["serde"] }
cyclonedx-bom = "0.4"
gloo-net = "0.3"
gloo-storage = "0.2.2"
gloo-utils = { version = "0.1", features = ["serde"] }
humansize = "2"
itertools = "0.11"
log = "0.4"
markdown = "1.0.0-alpha.11"
monaco = { version = "0.3", features = ["yew-components"] }
packageurl = "0.3"
patternfly-yew = { version = "0.5.0-alpha.3", features = ["icons-fab", "tree"] }
reqwest = { version = "0.11", features = ["json"] }
roxmltree = "0.18"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
sikula = { version = "0.4.0-alpha.5", features = ["time"] }
spdx-rs = "0.5.2"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
time = { version = "0.3", features = ["formatting", "macros", "wasm-bindgen"] }
url = { version = "2", features = ["serde"] }
urlencoding = "2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
yew = { version = "0.20", features = ["csr"] }
yew-hooks = "0.2"
yew-more-hooks = "0.2.0"
yew-nested-router = "0.2.2"
yew-oauth2 = { version = "0.6.2", features = ["router", "openid"] }

spog-model = "0.1.0"

bombastic-model = { path = "../../bombastic/model" }
vexination-model = { path = "../../vexination/model" }
trustification-api = { path = "../../api" }
trustification-common = { path = "../../common", default-features = false }
trustification-version = { path = "../../version" }

[build-dependencies]
trustification-version = { path = "../../version", features = ["build"] }

[dependencies.web-sys]
version = "0.3.61"
features = [
    "DataTransfer",
    "File",
]

[workspace]

[patch.crates-io]
#yew-nested-router = { path = "../yew-nested-router" }
#yew-nested-router = { git = "https://github.com/ctron/yew-nested-router", rev = "9689db446dee7030325884df768d0c2e84f353d6" }
#yew-more-hooks = { git = "https://github.com/ctron/yew-more-hooks", rev = "fc0af774aa925edcd5a544e562619ecb539942f8" }
#yew-more-hooks = { path = "../../../yew-more-hooks" }
patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", rev = "49f81fd7cd9101eacffb881497f00c6b0b637f2f" } # FIXME: awaiting release
#patternfly-yew = { path = "../../../patternfly-yew" }

csaf = { git = "https://github.com/voteblake/csaf-rs", rev = "76cb9ede10adb1fbb495b17e5fd8d95c5cf6c900" } # FIXME: waiting for release
monaco = { git = "https://github.com/siku2/rust-monaco", rev = "794a4cc7819f9ed7eb06559e24f75a41e23cf22a" } # FIXME: waiting for release

spog-model = { path = "../model" }

packageurl = { git = "https://github.com/ctron/packageurl.rs", rev = "c9a0c192ff0cba5d75b8cbf8be0b1e4dc14320aa" }

#sikula = { git = "https://github.com/ctron/sikula", rev = "65a13c415cbbc16e386b91f6b98a16a9ba3aa938"}

# also check root level Cargo.toml
cyclonedx-bom = { git = "https://github.com/trustification/cyclonedx-rust-cargo", branch = "trustification" }
spdx-rs = { git = "https://github.com/trustification/spdx-rs", rev = "f3f1ea9a72e270c8434f8be6ca1d61608b25b813" }

# release profile settings to reduce the final binary size
[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 's'
lto = true
