[package]
name = "spog-ui"
version = "0.1.0"
edition = "2021"
license = "Apache-2"
# Will be present in the about dialog too
description = "Single Pane of Glass"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["wasmbind"] }
cyclonedx-bom = "0.4"
gloo-net = "0.2"
gloo-utils = "0.1"
itertools = "0.10"
log = "0.4"
packageurl = "0.3"
patternfly-yew = { version = "0.5.0-alpha.1", features = ["icons-fab", "tree"] }
reqwest = { version = "0.11", features = ["json"] }
roxmltree = "0.18"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.24", features = ["derive"] }
thiserror = "1"
url = { version = "2", features = ["serde"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
yew = { version = "0.20", features = ["csr"] }
yew-hooks = "0.2"
yew-more-hooks = { version = "0.1.2", features = ["yew-hooks"] }
yew-nested-router = "0.2.1"
time = { version = "0.3", features = ["formatting", "macros"] }
csaf = { version = "0.5.0", default-features = false }

spog-model = "0.1.0"

[dependencies.web-sys]
version = "0.3.61"
features = [
    "DataTransfer",
    "File",
]

[workspace]

[patch.crates-io]
#yew-nested-router = { path = "../yew-nested-router" }
#yew-nested-router = { git = "https://github.com/ctron/yew-nested-router", rev = "9689db446dee7030325884df768d0c2e84f353d6" }
yew-more-hooks = { git = "https://github.com/ctron/yew-more-hooks", rev = "3c943759287c59a22256a4748993d2407b9a9e9b" }
#yew-more-hooks = { path = "../yew-more-hooks" }
patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", rev = "f271a6edb14ec9663e70a914f487cea0c15a9354" }
#patternfly-yew = { path = "../patternfly-yew" }

csaf = { git = "https://github.com/voteblake/csaf-rs", rev = "76cb9ede10adb1fbb495b17e5fd8d95c5cf6c900"} # FIXME: waiting for release

spog-model = { path = "../model" }

packageurl = { git = "https://github.com/ctron/packageurl.rs", rev = "c9a0c192ff0cba5d75b8cbf8be0b1e4dc14320aa" }
