[package]
name = "vexination-index"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
csaf = "0.5"
sikula = { version = "0.4.0", features = ["time"] }
time = "0.3"
trustification-api = { path = "../../api" }
trustification-index = { path = "../../index" }
vexination-model = { path = "../model" }
serde_json = "1"
cpe = "0.1.3"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
env_logger = "0.11"
