[package]
name = "collector"
version = "0.1.0"
edition = "2021"

[dependencies]
collector-osv = { path = "../osv" }
collector-snyk = { path = "../snyk" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"



