{{ if and .Values.v11y.walker.enabled .Values.v11y.walker.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: v11y-walker
  labels:
    app.kubernetes.io/name: v11y-walker
    app.kubernetes.io/component: walker
    app.kubernetes.io/part-of: trustification
spec:
  schedule: {{ .Values.v11y.walker.schedule | default "0 1 * * *" }}
  suspend: {{ .Values.v11y.walker.suspend | default false }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: v11y-walker
            app.kubernetes.io/component: walker
            app.kubernetes.io/part-of: trustification
        spec:
          restartPolicy: Never
          volumes:
            - name: cvelist
              persistentVolumeClaim:
                claimName: v11y-cvelist

          initContainers:
            - name: git-fetch
              image: "quay.io/trustification/git:2.40.1"
              volumeMounts:
                - mountPath: /git
                  name: cvelist
              command: ["/bin/sh"]
              args:
                - "-ec"
                - |
                  if test -d cvelistV5; then
                    cd cvelistV5
                    git pull
                  else
                    git clone https://github.com/CVEProject/cvelistV5
                  fi

          containers:
            - image: {{ .Values.trustImage }}:{{ .Values.release }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              name: walker
              volumeMounts:
                - mountPath: /mnt
                  name: cvelist
              command: ["/trust"]
              args:
                - "v11y"
                - "walker"
                - "--source"
                - "/mnt/cvelistV5"
                - "--delta-file"
                - "/mnt/last-delta"
              env:
                - name: RUST_LOG
                  value: {{ default "info" .Values.v11y.walker.logLevel }}
                - name: STORAGE_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Values.v11y.credentials }}"
                      key: aws_access_key_id
                - name: STORAGE_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Values.v11y.credentials }}"
                      key: aws_secret_access_key
                - name: STORAGE_REGION
                  value: "{{ .Values.region }}"
                - name: STORAGE_BUCKET
                  value: "{{ .Values.v11y.bucket }}"
                - name: INFRASTRUCTURE_ENABLED
                  value: "true"
                - name: INFRASTRUCTURE_BIND
                  value: "[::]:9010"
                {{ include "trustification.authentication-client" ( dict "root" . "clientId" "walker" ) | nindent 16 }}
              ports:
                - containerPort: 9010
                  protocol: TCP
                  name: infra
              resources:
                {{- toYaml .Values.v11y.walker.resources | nindent 16 }}
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: 9010
                initialDelaySeconds: 2
              readinessProbe:
                httpGet:
                  path: /health/ready
                  port: 9010
                initialDelaySeconds: 2
              startupProbe:
                httpGet:
                  path: /health/startup
                  port: 9010
{{ end }}
