{{- if and .Values.modules.v11yApi.enabled }}
{{- $mod := dict "root" . "name" "v11y-api" "component" "v11y" "module" .Values.modules.v11yApi -}}
{{- include "trustification.application.defaultService" $mod }}
{{- end }}