{{- if .Values.modules.guacGraphql.enabled }}
{{- $mod := dict "root" . "name" "guac" "component" "guac" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
data:
  guac.yaml: |
    # CSub setup
    csub-addr: "guac-collectsub.{{ .Release.Namespace }}.svc.cluster.local:2782"
    csub-listen-port: 2782

    # GQL setup
    gql-listen-port: 8080
    gql-test-data: false
    gql-addr: http://guac-graphql.{{ .Release.Namespace }}.svc:8080/query

    # Collector behavior
    service-poll: false
    use-csub: true
{{- end }}
