{{- if .Values.serviceMonitor.enabled }}
{{- $mod := dict "root" . "name" "monitoring" "component" "monitoring" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: 9010
    protocol: TCP
    targetPort: infra
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    metrics: "true"
  type: ClusterIP
{{- end }}
