[package]
name = "trustification-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-s3 = { git = "https://github.com/jcrossley3/rust-s3.git", branch = "issue-352" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
futures = "0.3"
bytes = "1"
http = "0.2"
async-stream = "0.3"
tracing = "0.1"
urlencoding = "2.1.2"
thiserror = "1"
async-compression = { version = "0.4", features = ["tokio", "zstd", "bzip2"] }
clap = { version = "4", features = ["derive", "env"] }
