collectors:
  osv: 
    url: http://collector-osv:8181/api/v1/
    interests:
    - package
    - vulnerability
  snyk: 
    url: http://collector-snyk:8182/api/v1/
    interests:
    - package
  nvd: 
    url: http://collector-nvd:8183/api/v1/
    interests:
    - vulnerability
