version: '3'
services:
  vexination-walker:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    command: vexination walker --devmode --workers 3 -3 --source https://www.redhat.com/.well-known/csaf/provider-metadata.json --sink http://vexination-api:$VEXINATION_API_PORT/api/v1/vex
    depends_on:
      minio:
        condition: service_healthy
    environment:
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"

  bombastic-walker:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    command: bombastic walker --devmode -3 --sink http://bombastic-api:$BOMBASTIC_API_PORT --scripts-path /usr/bin
    depends_on:
      bombastic-api:
        condition: service_healthy
    environment:
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"
