version: '3'
services:
  vexination-walker:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    command: vexination walker --devmode --workers 3 --source https://www.redhat.com/.well-known/csaf/provider-metadata.json -3 --storage-endpoint http://minio:9000
    depends_on:
      minio:
        condition: service_healthy

  bombastic-walker:
    image: $TRUST_IMAGE:${TRUST_VERSION:?}
    command: bombastic walker --bombastic-url http://bombastic-api:8080 --scripts-path /usr/bin
    depends_on:
      bombastic-api:
        condition: service_healthy
