version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    command: start-dev
    environment:
      - KEYCLOAK_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123456
    ports:
      - "8090:8080"
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  init-keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    depends_on:
      keycloak:
        condition: service_healthy # broken in podman, so we keep polling later on in the script
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KCADM_PATH=/opt/keycloak/bin/kcadm.sh
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123456
      - REALM=chicken
      - INIT_DATA=/init-sso/data
      - CHICKEN_ADMIN=admin
      - CHICKEN_ADMIN_PASSWORD=admin123456
    volumes:
      - ./container_files/init-sso:/init-sso:z
    entrypoint: /usr/bin/bash
    command: /init-sso/init.sh
