version: '3'
services:
  vexination-api:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    depends_on:
      - keycloak
    expose:
      - "$VEXINATION_API_PORT"
    ports:
      - "$VEXINATION_API_PORT:8080"
    command: vexination api --devmode --storage-endpoint http://minio:9000
    environment:
      ISSUER_URL: http://keycloak:8080/realms/chicken

  vexination-indexer:
    image: $TRUST_IMAGE:${TRUST_VERSION:?}
    command: vexination indexer --devmode --storage-endpoint http://minio:9000 --kafka-bootstrap-servers kafka:9094

  bombastic-api:
    image: $TRUST_IMAGE:${TRUST_VERSION:?}
    depends_on:
      - keycloak
    expose:
      - "$BOMBASTIC_API_PORT"
    ports:
      - "$BOMBASTIC_API_PORT:8080"
    command: bombastic api --devmode --storage-endpoint http://minio:9000
    environment:
      ISSUER_URL: http://keycloak:8080/realms/chicken

  bombastic-indexer:
    image: $TRUST_IMAGE:${TRUST_VERSION:?}
    command: bombastic indexer --devmode --storage-endpoint http://minio:9000 --kafka-bootstrap-servers kafka:9094

  spog-api:
    image: $TRUST_IMAGE:${TRUST_VERSION:?}
    depends_on:
      - keycloak
    expose:
      - "$SPOG_API_PORT"
    ports:
      - "$SPOG_API_PORT:8080"
    command: spog api --devmode --bombastic-url http://bombastic-api:8080 --vexination-url http://vexination-api:8080
    environment:
      ISSUER_URL: http://keycloak:8080/realms/chicken

  spog-ui:
    image: $TRUST_UI_IMAGE:${TRUST_VERSION:?}
    environment:
      - API_URL=http://localhost:$SPOG_API_PORT
      - BOMBASTIC_URL=http://localhost:$BOMBASTIC_API_PORT
      - VEXINATION_URL=http://localhost:$VEXINATION_API_PORT
      # the issuer URL is passed to the browser, which is running on the host, not insider the container, so the
      # URL is "localhost"
      - ISSUER_URL=http://localhost:8090/realms/chicken
    expose:
      - "$SPOG_UI_PORT"
    ports:
      - "$SPOG_UI_PORT:8080"
