version: '3'
services:
  jaeger:
    image: $JAEGER_IMAGE
    ports:
      - "6831:6831"
      - "6832:6832"
      - "5778:5778" # configs
      - "16686:16686" # server frontend
      - "14268:14268"
    environment:
      - LOG_LEVEL=debug
