version: '3'
services:
  vexination-walker:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    command: /trust vexination walker --devmode -3 --source https://www.redhat.com/.well-known/csaf/provider-metadata.json --sink http://vexination-api:$VEXINATION_API_PORT/api/v1/vex
    depends_on:
      minio:
        condition: service_healthy
    environment:
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"

  bombastic-walker:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    command: /trust bombastic walker --devmode -3 --signing-key https://access.redhat.com/security/data/97f5eac4.txt#77E79ABE93673533ED09EBE2DCE3823597F5EAC4 --source https://access.redhat.com/security/data/sbom/beta/ --sink http://bombastic-api:$BOMBASTIC_API_PORT/api/v1/sbom
    depends_on:
      bombastic-api:
        condition: service_healthy
    environment:
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"
