version: "3"

services:
  postgres:
    image: docker.io/library/postgres:16
    # If you wish to add additional configuration parameters to the database, uncomment the section below
    # The example below contains configuration for logging queries with duration longer than 500ms
    #command: postgres -c log_min_duration_statement=500 -c listen_addresses='*'
    environment:
      POSTGRES_USER: guac
      POSTGRES_DB: guac
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    expose:
      - "5432"
    #volumes:
      # - ./container_files/pg:/var/lib/postgresql/data${SELINUX_VOLUME_OPTIONS}
      # - ./container_files/guac/init.sql:/docker-entrypoint-initdb.d/init.sql${SELINUX_VOLUME_OPTIONS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guac -d guac"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 5

  guac-collectsub:
    image: $GUAC_IMAGE
    command: "/opt/guac/guaccsub --csub-listen-port $GUAC_CSUB_PORT"
    working_dir: /guac
    restart: on-failure
    expose:
      - "$GUAC_CSUB_PORT"
    ports:
      - "$GUAC_CSUB_PORT:$GUAC_CSUB_PORT"
    volumes:
      - ./container_files/guac:/guac${SELINUX_VOLUME_OPTIONS}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:$GUAC_CSUB_PORT"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  guac-graphql:
    image: $GUAC_IMAGE
    depends_on:
      postgres:
        condition: service_healthy
    command: "/opt/guac/guacgql --gql-listen-port $GUAC_API_PORT --gql-backend=ent --db-address=postgres://guac@postgres:5432/guac?sslmode=disable --db-driver=postgres --db-debug=true --gql-debug=true" #--db-migrate=false
    working_dir: /guac
    restart: on-failure
    expose:
      - "$GUAC_API_PORT"
    ports:
      - "$GUAC_API_PORT:$GUAC_API_PORT"
    volumes:
      - ./container_files/guac:/guac${SELINUX_VOLUME_OPTIONS}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:$GUAC_API_PORT"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  bombastic-collector:
    image: $GUAC_IMAGE
    command: "/opt/guac/guacone collect s3 --poll --s3-mp kafka --s3-url http://minio:9000 --s3-bucket bombastic --s3-queues sbom-indexed --s3-mp-endpoint kafka:9094 --gql-addr http://guac-graphql:$GUAC_API_PORT/query --csub-addr guac-collectsub:$GUAC_CSUB_PORT"
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: eu-west-1

  vex-collector:
    image: $GUAC_IMAGE
    command: "/opt/guac/guacone collect s3 --poll --s3-mp kafka --s3-url http://minio:9000 --s3-bucket vexination --s3-queues vex-indexed --s3-mp-endpoint kafka:9094 --gql-addr http://guac-graphql:$GUAC_API_PORT/query --csub-addr guac-collectsub:$GUAC_CSUB_PORT"
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: eu-west-1
