version: '3'
services:
  vexination-api:
    image: $TRUST_IMAGE
    expose:
      - "$VEXINATION_API_PORT"
    ports:
      - "$VEXINATION_API_PORT:8080"
    command: vexination api --devmode --storage-endpoint http://minio:9000
  vexination-indexer:
    image: $TRUST_IMAGE
    command: vexination indexer --devmode --storage-endpoint http://minio:9000 --kafka-bootstrap-servers kafka:9094
  vexination-walker:
    image: $TRUST_IMAGE
    command: vexination walker --devmode --source https://www.redhat.com/.well-known/csaf/provider-metadata.json -3 --storage-endpoint http://minio:9000
  bombastic-api:
    image: $TRUST_IMAGE
    expose:
      - "$BOMBASTIC_API_PORT"
    ports:
      - "$BOMBASTIC_API_PORT:8080"
    command: bombastic api --devmode --storage-endpoint http://minio:9000
  bombastic-indexer:
    image: $TRUST_IMAGE
    command: bombastic indexer --devmode --storage-endpoint http://minio:9000 --kafka-bootstrap-servers kafka:9094
  bombastic-exporter:
    image: $TRUST_IMAGE
    command: exporter --devmode --storage bombastic --storage-endpoint http://minio:9000 --kafka-bootstrap-servers kafka:9094 --guac-url nats:4222
  spog-api:
    image: $TRUST_IMAGE
    expose:
      - "$SPOG_API_PORT"
    ports:
      - "$SPOG_API_PORT:8088"
    command: spog api
