version: '3'

services:
  exhort-api:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    depends_on:
      - init-keycloak
      - collectorist-api
      - v11y-api
      - guac-graphql
    expose:
      - "$EXHORT_API_PORT"
    ports:
      - "$EXHORT_API_PORT:$EXHORT_API_PORT"
    command:
      - -c
      - |
        while [[ "$$(curl --connect-timeout 2 \
                  -s -o /dev/null -w ''%{http_code}'' \
                  $$OPENID_CONFIGURATION)" != "200" ]]; do
          echo waiting for keycloak...
          sleep 5
        done
        echo keycloak is up
        /trust exhort api -p $EXHORT_API_PORT --devmode
    entrypoint: /usr/bin/bash
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9010" ]
    environment:
      HTTP_SERVER_BIND_ADDR: "::"
      COLLECTORIST_URL: http://collectorist-api:$COLLECTORIST_API_PORT
      V11Y_URL: http://v11y-api:$V11Y_API_PORT
      GUAC_URL: http://guac-graphql:$GUAC_API_PORT/query
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"

  collectorist-api:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    depends_on:
      - init-keycloak
      - guac-collectsub
      - guac-graphql
    expose:
      - "$COLLECTORIST_API_PORT"
    ports:
      - "$COLLECTORIST_API_PORT:$COLLECTORIST_API_PORT"
    command:
      - -c
      - |
        while [[ "$$(curl --connect-timeout 2 \
                  -s -o /dev/null -w ''%{http_code}'' \
                  $$OPENID_CONFIGURATION)" != "200" ]]; do
          echo waiting for keycloak...
          sleep 5
        done
        echo keycloak is up
        /trust collectorist api \
          -p $COLLECTORIST_API_PORT \
          --collector-config /config/collectorist/collectorist.yaml \
          --devmode
    entrypoint: /usr/bin/bash
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9010" ]
    environment:
      HTTP_SERVER_BIND_ADDR: "::"
      CSUB_URL: http://guac-collectsub:$GUAC_CSUB_PORT
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"
    volumes:
      - ./container_files/collectorist:/config/collectorist${SELINUX_VOLUME_OPTIONS}

  collector-osv:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    depends_on:
      - init-keycloak
      - collectorist-api
      - v11y-api
    expose:
      - "$COLLECTOR_OSV_API_PORT"
    ports:
      - "$COLLECTOR_OSV_API_PORT:$COLLECTOR_OSV_API_PORT"
    command:
      - -c
      - |
        while [[ "$$(curl --connect-timeout 2 \
                  -s -o /dev/null -w ''%{http_code}'' \
                  $$OPENID_CONFIGURATION)" != "200" ]]; do
          echo waiting for keycloak...
          sleep 5
        done
        echo keycloak is up
        /trust collector osv \
          -p $COLLECTOR_OSV_API_PORT \
          --devmode
    entrypoint: /usr/bin/bash
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9010" ]
    environment:
      HTTP_SERVER_BIND_ADDR: "::"
      GUAC_URL: http://guac-graphql:$GUAC_API_PORT/query
      V11Y_URL: http://v11y-api:$V11Y_API_PORT/
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"


  collector-snyk:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    depends_on:
      - init-keycloak
      - collectorist-api
      - v11y-api
    expose:
      - "$COLLECTOR_SNYK_API_PORT"
    ports:
      - "$COLLECTOR_SNYK_API_PORT:$COLLECTOR_SNYK_API_PORT"
    command:
      - -c
      - |
        while [[ "$$(curl --connect-timeout 2 \
                  -s -o /dev/null -w ''%{http_code}'' \
                  $$OPENID_CONFIGURATION)" != "200" ]]; do
          echo waiting for keycloak...
          sleep 5
        done
        echo keycloak is up
        /trust collector snyk \
          -p $COLLECTOR_SNYK_API_PORT \
          --snyk-org-id $SNYK_ORG_ID \
          --snyk-token $SNYK_TOKEN \
          --devmode
    entrypoint: /usr/bin/bash
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9010" ]
    environment:
      GUAC_URL: http://guac-graphql:$GUAC_API_PORT/query
      HTTP_SERVER_BIND_ADDR: "::"
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"
