version: '3'

services:
  vexination-api:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    depends_on:
      - init-keycloak
    expose:
      - "$VEXINATION_API_PORT"
    ports:
      - "$VEXINATION_API_PORT:8080"
    command:
      - -c
      - |
        while [[ "$$(curl --connect-timeout 2 \
                  -s -o /dev/null -w ''%{http_code}'' \
                  $$OPENID_CONFIGURATION)" != "200" ]]; do
          echo waiting for keycloak...
          sleep 5
        done
        echo keycloak is up
        /trust vexination api --devmode --storage-endpoint http://minio:9000
    entrypoint: /usr/bin/bash
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9010" ]
    restart: on-failure
    environment:
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"

  vexination-indexer:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    command: vexination indexer --devmode --storage-endpoint http://minio:9000 --kafka-bootstrap-servers kafka:9094
    restart: on-failure

  bombastic-api:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    depends_on:
      - init-keycloak
    expose:
      - "$BOMBASTIC_API_PORT"
    ports:
      - "$BOMBASTIC_API_PORT:8080"
    command:
      - -c
      - |
        while [[ "$$(curl --connect-timeout 2 \
                  -s -o /dev/null -w ''%{http_code}'' \
                  $$OPENID_CONFIGURATION)" != "200" ]]; do
          echo waiting for keycloak...
          sleep 5
        done
        echo keycloak is up
        /trust bombastic api --devmode --storage-endpoint http://minio:9000
    entrypoint: /usr/bin/bash
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9010" ]
    environment:
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"

  bombastic-indexer:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    command: bombastic indexer --devmode --storage-endpoint http://minio:9000 --kafka-bootstrap-servers kafka:9094
    restart: on-failure

  spog-api:
    image: $TRUST_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    depends_on:
      - init-keycloak
      - bombastic-api
      - vexination-api
    expose:
      - "$SPOG_API_PORT"
    ports:
      - "$SPOG_API_PORT:8080"
    command:
      - -c
      - |
        while [[ "$$(curl --connect-timeout 2 \
                  -s -o /dev/null -w ''%{http_code}'' \
                  $$OPENID_CONFIGURATION)" != "200" ]]; do
          echo waiting for keycloak...
          sleep 5
        done
        echo keycloak is up
        /trust spog api --devmode --bombastic-url http://bombastic-api:8080 --vexination-url http://vexination-api:8080
    entrypoint: /usr/bin/bash
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9010" ]
    environment:
      ISSUER_URL: http://keycloak:8080/realms/chicken
      INFRASTRUCTURE_ENABLED: "true"
      OPENID_CONFIGURATION: "http://keycloak:8080/realms/chicken/.well-known/openid-configuration"

  spog-ui:
    image: $TRUST_UI_IMAGE:${TRUST_VERSION:?TRUST_VERSION is required}
    environment:
      - API_URL=http://localhost:$SPOG_API_PORT
      - BOMBASTIC_URL=http://localhost:$BOMBASTIC_API_PORT
      - VEXINATION_URL=http://localhost:$VEXINATION_API_PORT
      # the issuer URL is passed to the browser, which is running on the host, not insider the container, so the
      # URL is "localhost"
      - ISSUER_URL=http://localhost:8090/realms/chicken
    depends_on:
      - spog-api
    restart: on-failure
    expose:
      - "$SPOG_UI_PORT"
    ports:
      - "$SPOG_UI_PORT:8080"
