{{ if .Values.guac.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombastic-exporter
  labels:
    app.kubernetes.io/name: bombastic-exporter
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: trustification
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bombastic-exporter
      app.kubernetes.io/component: exporter
      app.kubernetes.io/part-of: trustification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bombastic-exporter
        app.kubernetes.io/component: exporter
        app.kubernetes.io/part-of: trustification
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - image: {{ .Values.trustImage }}:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: service
          command: ["/trust"]
          args:
            - "exporter"
            - "--event-bus"
            - "sqs"
            - "--stored-topic"
            - "{{ .Values.bombastic.exporter.topic }}"
            - "--storage-bucket"
            - "{{ .Values.bombastic.bucket }}"
            - "--guac-url"
            - "trustification-nats:4222"
            - "--document-type"
            - "sbom"
          env:
            - name: RUST_LOG
              value: {{ default "info" .Values.bombastic.exporter.logLevel }}
            - name: STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.bombastic.credentials }}"
                  key: aws_access_key_id
            - name: STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.bombastic.credentials }}"
                  key: aws_secret_access_key
            - name: STORAGE_REGION
              value: "{{ .Values.region }}"
            - name: STORAGE_BUCKET
              value: "{{ .Values.bombastic.bucket }}"
            - name: SQS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.bombastic.credentials }}"
                  key: aws_access_key_id
            - name: SQS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.bombastic.credentials }}"
                  key: aws_secret_access_key
            - name: SQS_REGION
              value: "{{ .Values.region }}"
            - name: INFRASTRUCTURE_ENABLED
              value: "true"
            - name: INFRASTRUCTURE_BIND
              value: "[::]:9010"
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9010
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9010
            initialDelaySeconds: 2
          startupProbe:
            httpGet:
              path: /health/startup
              port: 9010
{{ end }}
