[package]
name = "spog-ui-common"
version = "0.1.0"
edition = "2021"
license = "Apache-2"

[dependencies]
anyhow = "1"
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["wasmbind"] }
csaf = { version = "0.5.0", default-features = false }
cvss = { version = "2", features = ["serde"] }
gloo-events = "0.2"
gloo-net = "0.5.0"
gloo-storage = "0.3.0"
gloo-utils = { version = "0.2.0", features = ["serde"] }
humansize = "2"
itertools = "0.12"
js-sys = "0.3"
log = "0.4"
markdown = "1.0.0-alpha.11"
openidconnect = "3"
packageurl = "0.4"
patternfly-yew = { version = "0.6.0", features = ["icons-fab", "tree"] }
reqwest = { version = "0.11", features = ["json"] }
roxmltree = "0.19"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
spdx-rs = "0.5.5"
strum = { version = "0.26", features = ["derive"] }
thiserror = "1"
time = { version = "0.3", features = ["formatting", "macros", "wasm-bindgen"] }
url = { version = "2", features = ["serde"] }
urlencoding = "2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
yew = { version = "0.21", features = ["csr"] }
yew-consent = "0.2"
yew-hooks = "0.3"
yew-more-hooks = "0.3.0"
yew-nested-router = "0.7.0"
yew-oauth2 = { version = "0.11.0", features = ["yew-nested-router", "openid"] }

spog-model = { path = "../../../model" }

bombastic-model = { path = "../../../../bombastic/model" }
vexination-model = { path = "../../../../vexination/model" }
trustification-api = { path = "../../../../api" }
trustification-common = { path = "../../../../common", default-features = false }
trustification-version = { path = "../../../../version" }

[dependencies.web-sys]
version = "0.3.61"
features = [
    "DataTransfer",
    "File",
]
