{{- if .Values.modules.spogApi.enabled }}
{{- $mod := dict "root" . "name" "spog-api" "component" "spog" "module" .Values.modules.spogApi -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
  annotations:
    {{- include "trustification.application.annotations" $mod | nindent 4 }}

spec:
  replicas: {{ include "trustification.application.replicas" $mod }}
  selector:
    matchLabels:
      {{- include "trustification.common.selectorLabels" $mod | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trustification.common.selectorLabels" $mod | nindent 8 }}
        {{- include "trustification.application.podLabels" $mod | nindent 8 }}
      annotations:
        configHash/auth: {{ include (print $.Template.BasePath "/services/spog/api/020-ConfigMap-auth.yaml") . | sha256sum }}
        configHash/ui: {{ include (print $.Template.BasePath "/services/spog/api/020-ConfigMap-ui.yaml") . | sha256sum }}

    spec:
      {{- include "trustification.application.pod" $mod | nindent 6 }}

      containers:
        - name: service
          {{ include "trustification.common.defaultImage" $mod | nindent 10 }}
          {{- include "trustification.application.container" $mod | nindent 10 }}
          {{- include "trustification.application.infrastructure.probes" $mod | nindent 10 }}

          command: [ "/trust" ]
          args:
            - "spog"
            - "api"
            - "-p"
            - "8080"
            - "--db-storage-base"
            - "{{ include "trustification.preferences.db.path" $mod}}"
            - "--bombastic-url"
            - "{{ include "trustification.tls.http.protocol" $mod }}://bombastic-api.{{ .Release.Namespace }}.svc.cluster.local"
            - "--vexination-url"
            - "{{ include "trustification.tls.http.protocol" $mod }}://vexination-api.{{ .Release.Namespace }}.svc.cluster.local"
            - "--collectorist-url"
            - "{{ include "trustification.tls.http.protocol" $mod }}://collectorist-api.{{ .Release.Namespace }}.svc.cluster.local"
            - "--v11y-url"
            - "{{ include "trustification.tls.http.protocol" $mod }}://v11y-api.{{ .Release.Namespace }}.svc.cluster.local"
            - "--exhort-url"
            - "{{ include "trustification.tls.http.protocol" $mod }}://exhort-api.{{ .Release.Namespace }}.svc.cluster.local"
{{- with $mod.module.crdaUrl }}
            - "--crda-url"
            - {{ . | quote }}
{{- end }}
            - "--guac"
            - "{{ include "trustification.tls.http.protocol" $mod }}://guac-graphql.{{ .Release.Namespace }}.svc.cluster.local/query"
            - "--auth-configuration"
            - "/etc/config/auth.yaml"
          env:

            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            {{- include "trustification.application.rust.envVars" $mod | nindent 12 }}
            {{- include "trustification.application.infrastructure.envVars" $mod | nindent 12 }}
            {{- include "trustification.application.httpServer.envVars" $mod | nindent 12 }}
            {{- include "trustification.oidc.authenticationClient" ( dict "root" . "clientId" "walker" ) | nindent 12 }}
            {{- include "trustification.oidc.swaggerUi" $mod | nindent 12 }}

            {{- with $mod.module.snykToken }}
            - name: SNYK_TOKEN
              {{- include "trustification.common.envVarValue" . | nindent 14 }}
            {{- end }}

            {{- with $mod.module.segmentWriteKey }}
            - name: SEGMENT_WRITE_KEY
              {{- include "trustification.common.envVarValue" . | nindent 14 }}
            {{- end }}

            {{- if $mod.module.uiConfiguration }}
            - name: SPOG_UI_CONFIG
              value: /etc/config/spog-ui.yaml
            {{- end }}

            {{- if eq ( include "trustification.openshift.useServiceCa" .root ) "true" }}
            - name: CLIENT_TLS_CA_CERTIFICATES
              value: /run/secrets/kubernetes.io/serviceaccount/service-ca.crt
            {{- end }}

          ports:
            {{- include "trustification.application.infrastructure.podPorts" $mod | nindent 12 }}
            - containerPort: 8080
              name: endpoint
              protocol: TCP

          volumeMounts:
            {{- include "trustification.application.httpServerVolumesMounts" $mod | nindent 12 }}
            {{- include "trustification.authenticator.volumeMount" $mod | nindent 12 }}
            {{- include "trustification.preferences.db.volumeMount" $mod | nindent 12 }}
            {{- if $mod.module.uiConfiguration }}
            - name: config-ui
              mountPath: /etc/config/spog-ui.yaml
              subPath: {{ if ($mod.module.uiConfiguration.configMapRef).key }}{{ $mod.module.uiConfiguration.configMapRef.key }}{{ else }}spog-ui.yaml{{ end }}
            {{- end }}

            {{- include "trustification.application.extraVolumeMounts" $mod | nindent 12 }}

      volumes:
        {{- include "trustification.application.httpServerVolumes" $mod | nindent 8 }}
        {{- include "trustification.authenticator.volume" $mod | nindent 8 }}

        {{- if $mod.module.uiConfiguration }}
        - name: config-ui
          configMap:
            name: {{ with $mod.module.uiConfiguration.configMapRef }}{{ .name }}{{ else }}{{ include "trustification.common.name" (dict "root" . "name" "spog-ui-config" )}}{{ end }}
        {{- end }}

        {{- include "trustification.application.extraVolumes" $mod | nindent 8 }}
        {{- include "trustification.preferences.db.volume" $mod | nindent 8 }}

{{ end }}
