{{- if .Values.modules.guacCollectsub.enabled }}
{{- $mod := dict "root" . "name" "guac-collectsub" "component" "guac" "module" .Values.modules.guacCollectsub -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "trustification.common.selectorLabels" $mod | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              "kubernetes.io/metadata.name": {{ .Release.Namespace }}
{{- end }}
