[package]
name = "spog-ui-donut"
version = "0.1.0"
edition = "2021"
license = "Apache-2"

[dependencies]
gloo-utils = "0.2"
js-sys = "0.3"
serde_json = "1"
wasm-bindgen = "0.2"
yew = "0.21"

[dependencies.web-sys]
version = "0.3.61"
features = [
    "Element",
    "Node"
]
