{{ if .Values.guac.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guac-graphql
  labels:
    app.kubernetes.io/name: guac-graphql
    app.kubernetes.io/component: graphql
    app.kubernetes.io/part-of: trustification
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guac-graphql
      app.kubernetes.io/component: graphql
      app.kubernetes.io/part-of: trustification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guac-graphql
        app.kubernetes.io/component: graphql
        app.kubernetes.io/part-of: trustification
        metrics: "true"
      annotations:
        config/checksum: {{ include (print $.Template.BasePath "/config/020-ConfigMap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.guac.graphql.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.config.name }}
        - name: guac-config
          configMap:
            name: guac-cm
        {{ include "trustification.http-server-volumes" (dict "root" . "appName" "guac-graphql") | nindent 8 }}
      containers:
        - image: {{ .Values.guacImage }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: service
          command: ["/opt/guac/guacgql"]
          args:
{{- if .Values.guac.database.enabled  }}
            - "--gql-backend"
            - "ent"
            - "--db-address"
            - "postgres://$(DB_USER):$(DB_PASSWORD)@$(PGHOST):$(PGPORT)/$(DB_NAME)"
            - "--db-driver"
            - "postgres"
            - "--db-debug"
            - "true"
            - "--gql-debug"
            - "true"
{{- else }}
            - "--gql-backend"
            - "inmem"
            - "--gql-debug"
            - "true"
{{- end }}
          workingDir: "/guac"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{ include "trustification.http-server" . | nindent 12 }}
{{- if .Values.guac.database.enabled  }}
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: guac-user-db
                  key: "db.host"
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: guac-user-db
                  key: "db.port"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: guac-user-db
                  key: "db.name"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: guac-user-db
                  key: "db.user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: guac-user-db
                  key: "db.password"
{{- end }}
          volumeMounts:
            - name: guac-config
              mountPath: /guac
              readOnly: true
            - mountPath: /etc/config
              name: config
            {{ include "trustification.http-server-volume-mounts" . | nindent 12 }}
          resources:
            {{- toYaml .Values.guac.graphql.resources | nindent 12 }}
          ports:
            - containerPort: 8080
              protocol: TCP
{{ end }}
