[package]
name = "collector-snyk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
trustification-auth = { path = "../../auth" }
trustification-common = { path = "../../common" }
#trustification-collector-common = { path = "../common" }
trustification-infrastructure = { path = "../../infrastructure" }
#collectorist-api = { path = "../../collectorist/api"}
#collectorist-client = { path = "../../collectorist/client"}
collector-client = { path = "../client" }
v11y-client = { path = "../../v11y/client" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
log = "0.4"
utoipa = { version = "4", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "6", features = ["actix-web"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.44"
serde_json = "1.0.68"
guac = { workspace = true }
packageurl = "0.4"
reqwest = "0.11.18"
chrono = "0.4.26"
url-escape = "0.1.1"
regex = "1.9.3"
hide = "0.1"
url = "2"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.11"
test-with = { version = "0.12", features = ["runtime"] }
libtest-with = { version = "0.7.0-1", features = ["net", "resource", "user", "executable"] }

[build-dependencies]

#schemafy_lib = "0.6.0"
#tonic-build = "0.9.2"
