[package]
name = "spog-model"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

description = "The data model of the API"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["serde"] }
schemars = { version = "0.8", features = ["url"] }
serde = { version = "1", features = ["derive"] }
time = { version = "0.3" }
url = { version = "2", features = ["serde"] }
utoipa = { version = "3" }
vexination-model = { path = "../../vexination/model" }

# required by ToSchema utopia
serde_json = "1"
urlencoding = "2"

[dev-dependencies]
serde_json = "1"
anyhow = "1"