apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombastic-indexer
  labels:
    app.kubernetes.io/name: bombastic-indexer
    app.kubernetes.io/component: indexer
    app.kubernetes.io/part-of: bombastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bombastic-indexer
      app.kubernetes.io/component: indexer
      app.kubernetes.io/part-of: bombastic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bombastic-indexer
        app.kubernetes.io/component: indexer
        app.kubernetes.io/part-of: bombastic
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - image: ghcr.io/trustification/trust:latest
          imagePullPolicy: Always
          name: service
          command: ["/trust"]
          args: ["bombastic", "indexer", "--events", "sqs", "--index", "/data/index"]
          env:
            - name: RUST_LOG
              value: info
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: bombastic-credentials-secret
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: bombastic-credentials-secret
                  key: secret-access-key
            - name: AWS_REGION
              value: "eu-west-1"
          volumeMounts:
            - name: data
              mountPath: /data
