[package]
name = "trustification-infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
futures = "0.3"
serde_json = "1"
thiserror = "1.0"
tokio = { version = "1", features = ["time"] }
tracing = "0.1"
