apiVersion: batch/v1
kind: Job
metadata:
  name: vexination-walker
  labels:
    app.kubernetes.io/name: vexination-walker
    app.kubernetes.io/component: walker
    app.kubernetes.io/part-of: vexination
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vexination-walker
        app.kubernetes.io/component: walker
        app.kubernetes.io/part-of: vexination
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - image: ghcr.io/trustification/trust:latest
          imagePullPolicy: Always
          name: service
          command: ["/trust"]
          args: ["vexination", "walker", "--source", "https://www.redhat.com/.well-known/csaf/provider-metadata.json", "-3"]
          env:
            - name: RUST_LOG
              value: info
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: vexination-credentials-secret
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: vexination-credentials-secret
                  key: secret-access-key
          volumeMounts:
            - name: data
              mountPath: /data
