[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
env_logger = "0.10"
lazy_static = "1.4"
reqwest = { version = "0.11", features = ["json"] }
anyhow = "1"
openid = "0.12"
chrono = { version = "0.4", default-features = false }
log = "0.4"
test-context = "0.1"
test-with = "0.9"
ntest = "0.9"

bombastic-api = { path = "../bombastic/api" }
bombastic-indexer = { path = "../bombastic/indexer" }

vexination-api = { path = "../vexination/api" }
vexination-indexer = { path = "../vexination/indexer" }

spog-api = { path = "../spog/api" }

trustification-auth = { path = "../auth" }
trustification-event-bus = { path = "../event-bus" }
trustification-infrastructure = { path = "../infrastructure" }
trustification-storage = { path = "../storage" }
trustification-index = { path = "../index" }

[dev-dependencies]
env_logger = "0.10"
urlencoding = "2.1.2"
