parameters:
- name: BACKEND_IMAGE
  required: true
- name: FRONTEND_IMAGE
  required: true
- name: INTEGRATION_TESTS_IMAGE
  required: true
- name: IMAGE_TAG
  required: true
- name: REPLICAS
  value: "1"
- name: AWS_REGION
  required: true
- name: BOMBASTIC_STORAGE_BUCKET
  required: true
- name: BOMBASTIC_AWS_SECRET_NAME
  required: true
- name: BOMBASTIC_INDEXER_STORED_TOPIC
  required: true
- name: BOMBASTIC_INDEXER_INDEXED_TOPIC
  required: true
- name: BOMBASTIC_INDEXER_FAILED_TOPIC
  required: true
- name: BOMBASTIC_INDEXER_GUAC_TOPIC
  required: true
- name: BOMBASTIC_WALKER_RESOURCES
  required: true
- name: VEXINATION_STORAGE_BUCKET
  required: true
- name: VEXINATION_AWS_SECRET_NAME
  required: true
- name: VEXINATION_INDEXER_STORED_TOPIC
  required: true
- name: VEXINATION_INDEXER_INDEXED_TOPIC
  required: true
- name: VEXINATION_INDEXER_FAILED_TOPIC
  required: true
- name: VEXINATION_INDEXER_GUAC_TOPIC
  required: true
- name: ISSUER_URL
  required: true
- name: CONFIG_NAME
  required: true
- name: DOMAIN
  required: true
- name: BOMBASTIC_INDEXER_RESOURCES
  required: true
- name: BOMBASTIC_API_RESOURCES
  required: true
- name: VEXINATION_API_RESOURCES
  required: true
- name: VEXINATION_INDEXER_RESOURCES
  required: true
- name: SPOG_API_RESOURCES
  required: true
- name: SPOG_UI_RESOURCES
  required: true
- name: OIDC_PROVIDER_CLIENT_SECRET_NAME
  required: true
- name: OIDC_PROVIDER_CLIENT_SECRET_KEY
  required: true
- name: V11Y_API_RESOURCES
  required: true
- name: COLLECTORIST_RESOURCES
  required: true
- name: COLLECTOR_OSV_RESOURCES
  required: true
- name: COLLECTOR_SNYK_RESOURCES
  required: true
- name: COLLECTOR_NVD_RESOURCES
  required: true
- name: EXHORT_API_RESOURCES
  required: true
