apiVersion: apps/v1
kind: Deployment
metadata:
  name: vexination-indexer
  labels:
    app.kubernetes.io/name: vexination-indexer
    app.kubernetes.io/component: indexer
    app.kubernetes.io/part-of: vexination
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vexination-indexer
      app.kubernetes.io/component: indexer
      app.kubernetes.io/part-of: vexination
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vexination-indexer
        app.kubernetes.io/component: indexer
        app.kubernetes.io/part-of: vexination
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - image: ghcr.io/trustification/trust:latest
          imagePullPolicy: Always
          name: service
          command: ["/trust"]
          args: ["vexination", "indexer", "--events", "sqs", "--index", "/data/index"]
          env:
            - name: RUST_LOG
              value: info
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: vexination-credentials-secret
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: vexination-credentials-secret
                  key: secret-access-key
            - name: AWS_REGION
              value: "eu-west-1"
            - name: INFRASTRUCTURE_ENABLED
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9010
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9010
            initialDelaySeconds: 2
          startupProbe:
            httpGet:
              path: /health/startup
              port: 9010
