[package]
name = "spog-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

description = "An API server for trusted content"

[dependencies]
actix = "*"
actix-cors = "0.6"
actix-rt = "*"
actix-web = "4"
actix-web-httpauth = "0.8"
actix-web-extras = "0.1"
actix-web-prom = "0.6.0"
actix-ws = "*"
anyhow = "1"
derive_more = "0.99"
bytes = "1"
chrono = "0.4.23"
clap = { version = "4.0.29", features = ["derive"] }
env_logger = "0.10"
futures = "0.3"
guac = "0.1"
http = "*"
log = "0.4"
mime = "0.3.16"
okapi = "0.7.0-rc.1"
packageurl = { version = "0.3", features = ["serde"] }
prometheus = "0.13.3"
rand = "0.8"
reqwest = { version = "0.11.16", features = ["stream"] }
serde = { version = "1.0.152" }
serde_json = "1.0.89"
serde_yaml = "0.9"
snyk = { git = "https://github.com/dejanb/snyk-rs.git", branch = "main" }
thiserror = "1"
tracing = "0.1"
tokio = { version = "*", features = ["rt", "fs", "macros", "rt-multi-thread"] }
url = "2"
urlencoding = "2.1.2"
utoipa = { version = "3", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "3", features = ["actix-web"] }
zstd = "0.12"

#guac = { path = "../guac-rs/lib" }
spog-model = { path = "../model" }
vexination-model = { path = "../../vexination/model" }
bombastic-model = { path = "../../bombastic/model" }

trustification-api = { path = "../../api" }
trustification-common = { path = "../../common" }
trustification-infrastructure = { path = "../../infrastructure" }
trustification-version = { path = "../../version", features = ["actix-web"] }
trustification-auth = { path = "../../auth", features = ["actix", "swagger"] }

[build-dependencies]
trustification-version = { path = "../../version", features = ["build"] }
