[package]
name = "exhort-model"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
packageurl = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
utoipa = "3"

trustification-common = { path = "../../common" }
trustification-infrastructure = { path = "../../infrastructure" }
trustification-auth = { path = "../../auth" }
v11y-model = { path = "../../v11y/model" }