[package]
name = "trustification-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Common API definitions"

[dependencies]
reqwest = { version = "0.11", default-features = false}
serde = { version = "1", features = ["derive"] }
utoipa = "3"