name: CI

on:
  push:
    # Run on the main branch
    branches:
      - main
  # Also on PRs, just be careful not to publish anything
  pull_request:
  # And merge queues
  merge_group:
    types: [checks_requested]
  # Allow to be called from other workflows (like "release")
  workflow_call:
  # But don't trigger on tags, as they are covered by the "release.yaml" workflow

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            bommer/bommer-ui/target/
            spog/ui/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Check formatting
        run: |
          cargo fmt --check
          cargo fmt --check --manifest-path bommer/bommer-ui/Cargo.toml
          cargo fmt --check --manifest-path spog/ui/Cargo.toml

      - name: Check clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Check
        run: cargo check

      - name: Check (frontend)
        run: |
          cargo check --manifest-path bommer/bommer-ui/Cargo.toml
          cargo check --manifest-path spog/ui/Cargo.toml

      - name: Test
        run: cargo test

      - name: Test (frontend)
        run: |
          cargo test --manifest-path bommer/bommer-ui/Cargo.toml
          cargo test --manifest-path spog/ui/Cargo.toml

  integration:
    uses: ./.github/workflows/integration.yaml

