name: Integration Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            bommer/bommer-ui/target/
            spog/ui/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compose
        run: |
          docker-compose -f deploy/compose/compose.yaml -f deploy/compose/compose-guac.yaml up -d

      - name: Test
        run: |
          RUST_LOG=tantivy=off,info cargo test -p integration-tests -- --nocapture
          docker-compose -f deploy/compose/compose.yaml -f deploy/compose/compose-guac.yaml ps

      - name: Print logs
        if: always()
        run: |
          docker ps -a
          docker-compose -f deploy/compose/compose.yaml -f deploy/compose/compose-guac.yaml logs
          docker-compose -f deploy/compose/compose.yaml -f deploy/compose/compose-guac.yaml down
