on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  notify_channel:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft == false
    steps:
      - name: Send message
        env:
          PASSWORD: ${{ secrets.MATRIX_BOT_PASSWORD }}
        run: |
          podman run --rm docker.io/matrixcommander/matrix-commander:latest --login password --homeserver https://matrix.org --device github --user-login @trustification-bot:matrix.org --password "$PASSWORD" --room-default '#trustification:matrix.org' --message "New PR opened: ${{ github.event.pull_request.html_url }}"  --logout me
